services:
  # =============================================================================
  # Core Database Services
  # =============================================================================
  postgres:
    image: postgres:15-alpine
    container_name: refurbix-postgres
    environment:
      POSTGRES_DB: refurbix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d:ro
    networks:
      - refurbix-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d refurbix"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: refurbix-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - refurbix-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # =============================================================================
  # Development Tools
  # =============================================================================
  pgadmin:
    image: dpage/pgadmin4:8.2
    container_name: refurbix-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@refurbix.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_DISABLE_POSTFIX: "true"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - refurbix-network
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: refurbix-mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - refurbix-network
    restart: unless-stopped

  # =============================================================================
  # Monitoring
  # =============================================================================
  influxdb:
    image: influxdb:2.7-alpine
    container_name: refurbix-influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD:-password}
      DOCKER_INFLUXDB_INIT_ORG: refurbix
      DOCKER_INFLUXDB_INIT_BUCKET: metrics
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN:-dev-token}
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - refurbix-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

# =============================================================================
# Networks & Volumes
# =============================================================================
networks:
  refurbix-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:
  influxdb_data: