# RefurbiX Prometheus Configuration
# ==============================================================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kong'
    static_configs:
      - targets: ['api-gateway:8001']
    metrics_path: /metrics

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3001']
    metrics_path: /metrics

  - job_name: 'audit-service'
    static_configs:
      - targets: ['audit-service:3002']
    metrics_path: /metrics

  - job_name: 'device-service'
    static_configs:
      - targets: ['device-service:3003']
    metrics_path: /metrics

  - job_name: 'workflow-service'
    static_configs:
      - targets: ['workflow-service:3004']
    metrics_path: /metrics

  - job_name: 'reporting-service'
    static_configs:
      - targets: ['reporting-service:3005']
    metrics_path: /metrics

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:3006']
    metrics_path: /metrics

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']